# Pull tomcat latest image from dockerhub 
From tomcat:latest

# Maintainer
MAINTAINER "AR Shankar" 

# copy war file on to container 
COPY /root/.jenkins/workspace/sample/webapp/target/webapp.war /usr/local/tomcat/webapps
